version: 1.2
# testing other ccmment
workflows:
   - subclass: GALAXY
     primaryDescriptorPath: /Dockstore.gxwf.yml
     # testing more comment
     testParameterFiles:
      - /Dockstore.gxwf-test.yml
